
[tool.poetry]
name = "dlme-airflow"
version = "0.1.0"
description = "ETL Pipeline management for the Digital Library of the Middle East (DLME)"
authors = ["Aaron Collier <aaron.collier@stanford.edu>"]
license = "Apache2"

[tool.poetry.dependencies]
python = "^3.9"
lxml = "^4.6.3"
Sickle = "^0.7.0"
intake = "^0.6.2"
aiohttp = "^3.7.4.post0"
jsonpath_ng = "^1.5.3"
apache-airflow = "^2.1.3"
feedparser = "^6.0.2"
validators = "^0.18.2"
dominate = "^2.6.0"
pandas = "^1.4.1"
beautifulsoup4 = "^4.11.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.7b0"
pytest = "^6.2.4"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
