
[tool.poetry]
name = "dlme-airflow"
version = "0.1.0"
description = "ETL Pipeline management for the Digital Library of the Middle East (DLME)"
authors = ["Aaron Collier <aaron.collier@stanford.edu>"]
license = "Apache2"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
