version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  test:
    jobs:
      - lint_and_test

jobs:
  lint_and_test:
    docker:
      - image: apache/airflow:2.1.2-python3.8

    steps:
      - checkout

      # Install dependencies
      - python/install-packages:
          pkg-manager: pip

      #  Run flake8 linter
      - run:
          name: Run linter
          command: flake8

      # Run tests
      - run:
          name: Run tests
          command: PYTHONPATH=dlme_airflow pytest
