version: 2.1

orbs:
  python: circleci/python@2.1.1
  codecov: codecov/codecov@5

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: suldlss/dlme-airflow
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build_test_and_lint:
    executor:
      name: python/default
      tag: "3.12"
    steps:
      - run:
          name: Install PIP
          command: |
            pip install uv
      - checkout
      - run:
          name: Setup venv
          command: |
            uv venv
      - run:
          name: Activate venv
          command: |
            source .venv/bin/activate
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
      - run:
          name: Lint the code with ruff
          command: |
             ruff check
      - run:
          name: Run tests
          command: |
             pytest --cov
      - codecov/upload
  publish_to_dockerhub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
             docker build . -t $IMAGE_NAME:latest

      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build:
    jobs:
      - build_test_and_lint
      - publish_to_dockerhub:
          filters:
            branches:
              only: main
