#!/bin/bash

# This script is called by our weekly dependency update job in Jenkins, before updating Ruby and other deps

# Without these ENV changes, python gets confused and tries to use latin1
# encodings which breaks the updates below
export LANG=en_US.UTF-8
export LC_COLLATE=C.UTF-8

# Needed to successfully run `pipx`-installed executables
export PATH="$HOME/.local/bin:$PATH"

pip3 install --user pipx > dlme-airflow.txt &&
    pipx install uv --force >> dlme-airflow.txt &&
    uv venv &&
    uv pip compile pyproject.toml -o requirements.txt --upgrade -q --no-progress --color never >> dlme-airflow.txt

retVal=$?

git add requirements.txt &&
    git commit -m "Update Python dependencies"

if [ $retVal -ne 0 ]; then
    echo "ERROR UPDATING PYTHON (dlme-airflow)"
    cat dlme-airflow.txt
fi
